variable "public-subnet-name1" {}
variable "public-subnet-name2" {}
variable "web-subnet1" {}
variable "web-subnet2" {}
variable "web-alb-sg-name" {}
variable "app-alb-sg-name" {}
variable "web-alb-name" {}
variable "app-alb-name" {}
variable "web-tg-name" {}
variable "app-tg-name" {}
variable "vpc-name" {}