variable "sg-name" {}
variable "db-subnet-name1" {}
variable "db-subnet-name2" {}
variable "db-sg-name" {}
variable "rds-username" {}
variable "rds-pwd" {}
variable "db-name" {}
variable "rds-name" {}
variable "db-subnet-group-name" {}